development: &local
  email:
    sender: noreply@mightbuy.it
  app_url: "http://localhost:3000"
  invite_url: "http://localhost:3100/invite"

test:
  <<: *local

production:
  <<: *local
  email:
    sender: noreply@mightbuy.it
  app_url: "https://www.mightbuy.it"
  invite_url: "http://www.mightbuy.it/invite"
  